### ISSUE TITLE
Verify and quantify performance improvement of using Cython

### ISSUE THREAD

**Issue by adonath** [xpsi-group/neost#63]
In the documentation there is the statement (https://xpsi-group.github.io/neost/install.html#installing-neost):

> NEoST can optionally be installed without cythonizing the TOV solvers, at the expense of much slower performance. 

While the statement is often generally true, it would be good to provide the users with some numbers in order to make an informed decision. I would suggest a minimal table in the document and / or `README.md` comparing the numbers on at least one of the example analyses. There is no need for a high precision profiling, but just getting the order of magnitude right. I.e. is the performance improvement 3x, 10x or 100x.

**Comment by svisak** [comment]
Good idea, I'll run a representative test and provide the overall speedup I experience. This will of course be very approximate and case-dependent but a rough estimate is better than just saying "it's faster".

**Comment by nr1118** [comment]
Okay, I have completed a speed-up test comparing Cython to Python. I have updated the documentation and README to reflect this, see Pull request #66.
